import { T } from "./theme";

export const SERVICES = [
  { id: 1, name: "Plumbing", count: 143, grad: "linear-gradient(135deg,#FF6B35,#F7931E)" },
  { id: 2, name: "Electrical", count: 98, grad: "linear-gradient(135deg,#F7971E,#FFD200)" },
  { id: 3, name: "Cleaning", count: 215, grad: "linear-gradient(135deg,#11998E,#38EF7D)" },
  { id: 4, name: "Tutoring", count: 87, grad: "linear-gradient(135deg,#667EEA,#764BA2)" },
  { id: 5, name: "Painting", count: 62, grad: "linear-gradient(135deg,#FC466B,#3F5EFB)" },
  { id: 6, name: "Gardening", count: 54, grad: "linear-gradient(135deg,#56ab2f,#a8e063)" },
  { id: 7, name: "Carpentry", count: 71, grad: "linear-gradient(135deg,#F7971E,#FFD200)" },
  { id: 8, name: "AC Repair", count: 119, grad: "linear-gradient(135deg,#4facfe,#00f2fe)" },
];

export const PROVIDERS = [
  {
    id: 1,
    name: "Rajesh Kumar",
    service: "Plumbing",
    rating: 4.9,
    reviews: 312,
    price: 350,
    available: true,
    distance: "1.2 km",
    initials: "RK",
    grad: "orange",
    verified: true,
    jobs: 890,
    bio: "10+ yrs · Licensed & insured",
  },
  {
    id: 2,
    name: "Sita Sharma",
    service: "Cleaning",
    rating: 4.8,
    reviews: 245,
    price: 280,
    available: true,
    distance: "0.8 km",
    initials: "SS",
    grad: "green",
    verified: true,
    jobs: 650,
    bio: "Professional deep cleaner",
  },
  {
    id: 3,
    name: "Arun Thapa",
    service: "Electrical",
    rating: 4.7,
    reviews: 189,
    price: 400,
    available: false,
    distance: "2.1 km",
    initials: "AT",
    grad: "blue",
    verified: true,
    jobs: 420,
    bio: "Certified electrician",
  },
  {
    id: 4,
    name: "Priya Devi",
    service: "Tutoring",
    rating: 5.0,
    reviews: 98,
    price: 500,
    available: true,
    distance: "1.5 km",
    initials: "PD",
    grad: "purple",
    verified: false,
    jobs: 180,
    bio: "MSc Math · 5★ rated tutor",
  },
  {
    id: 5,
    name: "Bikram Rai",
    service: "Painting",
    rating: 4.6,
    reviews: 134,
    price: 320,
    available: true,
    distance: "3.0 km",
    initials: "BR",
    grad: "pink",
    verified: true,
    jobs: 290,
    bio: "Interior & exterior specialist",
  },
  {
    id: 6,
    name: "Suman Gurung",
    service: "Gardening",
    rating: 4.9,
    reviews: 76,
    price: 250,
    available: true,
    distance: "0.5 km",
    initials: "SG",
    grad: "green",
    verified: false,
    jobs: 145,
    bio: "Garden design & care",
  },
];

export const BOOKINGS = [
  {
    id: "#BK2401",
    service: "Plumbing",
    provider: "Rajesh Kumar",
    date: "Apr 12, 2025",
    time: "10:00 AM",
    status: "confirmed",
    amount: 350,
    address: "Thamel, KTM",
  },
  {
    id: "#BK2398",
    service: "Cleaning",
    provider: "Sita Sharma",
    date: "Apr 8, 2025",
    time: "2:00 PM",
    status: "completed",
    amount: 560,
    address: "Lazimpat, KTM",
  },
  {
    id: "#BK2384",
    service: "Electrical",
    provider: "Arun Thapa",
    date: "Mar 28, 2025",
    time: "11:00 AM",
    status: "completed",
    amount: 800,
    address: "Baneshwor, KTM",
  },
  {
    id: "#BK2370",
    service: "Tutoring",
    provider: "Priya Devi",
    date: "Mar 20, 2025",
    time: "4:00 PM",
    status: "cancelled",
    amount: 500,
    address: "Online",
  },
];

export const NOTIFS = [
  { id: 1, icon: "📍", msg: "Rajesh Kumar is on the way", time: "2 min ago", read: false, color: T.orange },
  {
    id: 2,
    icon: "💳",
    msg: "Payment of NPR 350 confirmed",
    time: "10 min ago",
    read: false,
    color: T.teal,
  },
  { id: 3, icon: "⭐", msg: "Sita Sharma gave you 5 stars!", time: "1 hr ago", read: true, color: T.warning },
  {
    id: 4,
    icon: "✅",
    msg: "Booking #BK2405 accepted",
    time: "2 hr ago",
    read: true,
    color: T.success,
  },
];

export const STATUSES = {
  confirmed: { bg: "rgba(79,172,254,0.13)", color: "#4facfe", dot: "#4facfe", label: "Confirmed" },
  completed: { bg: "rgba(56,239,125,0.11)", color: "#38EF7D", dot: "#38EF7D", label: "Completed" },
  cancelled: { bg: "rgba(252,70,107,0.11)", color: "#FC466B", dot: "#FC466B", label: "Cancelled" },
  pending: { bg: "rgba(255,210,63,0.11)", color: "#FFD23F", dot: "#FFD23F", label: "Pending" },
};
